# CodeRabbit Configuration
# https://docs.coderabbit.ai/reference/configuration

reviews:
  # Request changes (blocking) instead of just commenting when issues found
  request_changes_workflow: true
  high_level_summary: true
  # Disable docstring coverage check (we don't enforce JSDoc in this project)
  pre_merge_checks:
    docstrings:
      mode: "off"
  auto_review:
    enabled: true
    drafts: false
    # Review all PRs except those with 'skip-review' label
    labels:
      - "!skip-review"

  path_instructions:
    - path: "**/*.md"
      instructions: "Focus on clarity, grammar, and accuracy. Light touch for docs."

chat:
  auto_reply: true
