# CodeRabbit Configuration
# https://docs.coderabbit.ai/reference/configuration

reviews:
  auto_review:
    enabled: true
    drafts: false
    # Skip review when 'skip-review' label is present (! = negative match)
    labels:
      - "!skip-review"

  path_instructions:
    - path: "**/*.md"
      instructions: "Focus on clarity, grammar, and accuracy. Light touch for docs."

chat:
  auto_reply: true
